script:
  - npm run init
  - npm run build
  - echo 'lunchbox.qnv.pw' > ./docs/CNAME
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git pull
  - git push https://$github_id:$github_pass@github.com/qnaiv/tech-lunch-box.git master
