script:
  - npm run init
  - npm run build
  - echo 'lunchbox.qnv.pw' > ./docs/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local-dir: docs
  on:
    branch: master