
language: node_js
before_install:
  - openssl aes-256-cbc -K $encrypted_0975109d8020_key -iv $encrypted_0975109d8020_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key

script:
  - npm run init
  - npm run build
  - echo 'lunchbox.qnv.pw' > ./docs/CNAME
  - git init
  - git add -A
  - git commit -m 'deploy'
  - if [ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git push -f git@github.com:qnaiv/tech-lunch-box.git master:gh-pages;
    fi